modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "scribe_test"
version = "${version}"
displayName = "Scribe Test"
authors = '''
Team Abode
ExDrill
OuterCloudStudio
'''
description = '''
Library for the Team Abode mods.
'''
logoFile = "icon.png"

[[dependencies.scribe_test]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scribe_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"