modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="scribe"
version="${file.jarVersion}"
displayName="Scribe"
logoFile="icon.png"
credits='''
ExDrill
OuterCloudStudio
'''
authors="Team Abode"
description='''
A library designed for multi-loader projects, mainly used by Team Abode.
'''
[[dependencies.scribe]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scribe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
