name: Publish
on: [ workflow_dispatch ]

env:
  MOD_NAME: Sketch
  MINECRAFT_VERSION: 1.21
  JAVA_VERSION: 21
  MOD_VERSION: 1.2.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check environment variables
        run: env

      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew clean build

      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: "${{env.MOD_NAME}} ${{env.MINECRAFT_VERSION}}-${{env.MOD_VERSION}}"
          version: "${{env.MINECRAFT_VERSION}}-${{env.MOD_VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          github-tag: "${{env.MINECRAFT_VERSION}}-${{env.MOD_VERSION}}"
          curseforge-token: "${{secrets.PUBLISH_CURSEFORGE_TOKEN}}"
          modrinth-token: "${{secrets.PUBLISH_MODRINTH_TOKEN}}"
          github-token: "${{secrets.PUBLISH_GITHUB_TOKEN}}"